### ISSUE TITLE
Fails to build with HDF 4.4.0

### ISSUE THREAD

**Issue by sebastic** [stcorp/coda#110]
coda fails to build with HDF 4.4.0 as reported in [Debian Bug #1146646](https://bugs.debian.org/1146646):
> Your package FTBFS with HDF 4.4.0:
> ```
> ../../libcoda/coda-hdf4-type.c: In function 'coda_hdf4_Vgroup_new':
> ../../libcoda/coda-hdf4-type.c:1813:9: error: too few arguments to function 'Vinquire'; expected 4, have 3
>  1813 |     if (Vinquire(type->vgroup_id, &num_entries, type->vgroup_name) != 0)
>       |         ^~~~~~~~
> In file included from /usr/include/hdf/hdf.h:192,
>                  from ../../libcoda/coda-hdf4-internal.h:38,
>                  from ../../libcoda/coda-hdf4-type.c:32:
> /usr/include/hdf/hproto.h:1409:15: note: declared here
>  1409 | HDFLIBAPI int Vinquire(int32 vkey, int32 *nentries, char *vgname, size_t *buf_size);
>       |               ^~~~~~~~
> ../../libcoda/coda-hdf4-type.c:1820:9: error: too few arguments to function 'Vgetclass'; expected 3, have 2
>  1820 |     if (Vgetclass(type->vgroup_id, type->classname) != 0)
>       |         ^~~~~~~~~
> /usr/include/hdf/hproto.h:1407:15: note: declared here
>  1407 | HDFLIBAPI int Vgetclass(int32 vkey, char *vgclass, size_t *buf_size);
>       |               ^~~~~~~~~
> ```
> The full buildlog is attached.
> [coda_2.25.6-3.1_amd64.build](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=1146646;filename=coda_2.25.6-3.1_amd64.build;msg=5)
